apiVersion: v1
kind: ConfigMap
metadata:
  name: skys-scraper-db-init
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS `skys-scraper`;
    CREATE USER 'skys-scraper'@'%' IDENTIFIED BY 'password';
    GRANT ALL ON skys.* TO 'skys-scraper'@'%';

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: skys-scraper-db-conf
data:
  my.cnf: |
    [mysqld]
    # mysqlサーバー側が使用する文字コード
    character-set-server=utf8mb4

    # テーブルにTimeStamp型のカラムをもつ場合、推奨
    explicit-defaults-for-timestamp=1

    # 実行したクエリの全ての履歴が記録される（defaultではOFFになっているらしい）
    general-log=1

    # ログの出力先
    general-log-file=/var/log/mysql/mysqld.log

    [client]
    # mysqlのクライアント側が使用する文字コード
    default-character-set=utf8mb4