apiVersion: apps/v1
kind: Deployment
metadata:
  name: skys-scraper-app-dep
spec:
  selector:
    matchLabels:
      app: skys-scraper-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: skys-scraper-app-pod
      labels:
        app: skys-scraper-app
    spec:
      containers:
        - name: skys-scraper-app
          image: skys-scraper:puppeteer-with-nestjs
          imagePullPolicy: Never
          volumeMounts:
            - name: skys-scraper-app
              mountPath: /var/www
            - name: skys-scraper-app-npm-log
              mountPath: /root/.npm/_logs
          ports:
            - containerPort: 3000
      volumes:
        - name: skys-scraper-app
          hostPath:
            path: {{ .Values.container.volume.project_root_path }}
            type: DirectoryOrCreate
        - name: skys-scraper-app-npm-log
          hostPath:
            path: {{ .Values.container.volume.project_root_path }}/logs/npm
            type: DirectoryOrCreate